### ISSUE TITLE
Unable to < make repl > 

### ISSUE THREAD

**Issue by abhi18av** [clojerl/clojerl#577]
Hi Clojerl team,

For some reason I'm unable to simply `make repl` 

Here's my error log 

```
rlwrap: error:
  prompt colour spec should be <attr>;<fg>[;<bg>]
  where <attr> ranges over [0...8], <fg> over [30...37] and <bg> over [40...47]
  example: 0;33 for yellow on current background, 1;31;40 for bold red on black
Makefile:34: recipe for target 'repl' failed
make: *** [repl] Error 1

```

I'm on Ubuntu16.04 and relying on `nix` package manager for the `erlang` and `rebar3` dependencies

**Comment by jfacorro** [comment]
@abhi18av This seems like an issue with `rlwrap` related to color representation in the terminal (see [here](https://github.com/andreyvit/rlwrap/blob/master/src/readline.c#L605)).

What happens if you run the following?
```
rlwrap bin/clojerl -r
```
In the meantime if you would like to try the REPL, please try running: 
```
bin/clojerl -r
```
This should bring up the Clojerl prompt.

**Comment by abhi18av** [comment]
Yup, the `rlwrap bin/clojerl -r` command works perfectly and I see the following

``` 
Clojure 0.3.0-1563.8ccda64
clje.user=> (+ 1 1 )
2
```


However, is there a way this could be resolved permanently  ?

**Comment by jfacorro** [comment]
The problem here is different behaviours between the Mac OS X and the Ubuntu implementations for `rlwarp`.

I think a way towards a solution would be to either figure out a common way of detecting the presence of `rlwrap` that's implementation independent or detect the implementation and use it `rlwrap` accordingly. 

PRs are welcome! 😄

**Comment by jfacorro** [comment]
@abhi18av There's a PR with a possible fix. It turns out the problem was that in the Makefile the shell used by default is `sh` which has a different implementation of the builtin `type` command in Ubuntu (maybe all Linux) but not in Mac OS X.

**Comment by abhi18av** [comment]
Ohh, I see!

Thanks for working on this amazing idea of `clojure and erlang` @jfacorro  👍
