### ISSUE TITLE
Inquiry: can Cider IDE be used with Clojerl?

### ISSUE THREAD

**Issue by mdbergmann** [clojerl/clojerl#671]
Hi,

I was wondering which IDE or editor can be used that gives completion and syntax highlighting, etc.

Manfred

**Comment by jfacorro** [comment]
I'm currently using Emacs with clojure-mode and a running REPL.  

I haven't had time to try to implement an nREPL backend for CIDER, I still have that in my TODO list 😔.

![Screenshot 2019-12-12 at 10 42 01](https://user-images.githubusercontent.com/1522569/70701201-408b5280-1ccc-11ea-94c2-e0cd71e44ed0.png)

**Comment by jfacorro** [comment]
I think it's a good idea to try to implement an nREPL backend.

**Comment by mdbergmann** [comment]
Do you know what the general approach would be? Briefly explained.
Maybe I have some time over Christmas/New Year to dig a bit.

**Comment by jfacorro** [comment]
I'll investigate and come back to you with some more information.

**Comment by jfacorro** [comment]
@mdbergmann I have spent some time looking into CIDER code and the nREPL protocol.

From what I could gather CIDER seems to be implemented to support a specific number of build tools for Clojure JVM and ClojureScript (see [here](https://github.com/clojure-emacs/cider/blob/71e737ac92193bfce46dcca3f0f85270729eb64c/cider.el#L325)). To be able to use CIDER, it would be necessary to include support for `rebar3` projects, and most likely more work that I'm not aware of since I'm not that familiar with CIDER's code. Some CIDER features might not work with Clojerl because of the differences between this project and Clojure itself, but I can't think off the top of my head what would those be.

The nREPL protocol seems to be fairly simple and according to the documentation is actually [language agnostic](https://nrepl.org/nrepl/0.6.0/index.html#_beyond_clojure). There seems to be a number of [implementations for other languages](https://nrepl.org/nrepl/0.6.0/beyond_clojure.html), some of which could server as a guide to implement this in Clojerl. To avoid implementing the nREPL server from scratch it should be possible to port the [current Clojure JVM implementation](https://github.com/nrepl/nrepl/tree/master/src/clojure/nrepl). It seems to be quite self-contained, since it has no dependencies listed in its `project.clj`.

Porting the library would roughly mean:
- Adding a `rebar.config` file that include `clojerl` as a dep and the `rebar3_clojerl` plugin. 
- Creating a `nrepl.app.src` file under the `src` folder.
- Changing the extension of files from `.clj` to `.cljc`.
- Replacing all Java specific interop code in the `.cljc` files with Erlang interop code, and also replacing Clojure classes with Clojerl types that implement them.

**Comment by mdbergmann** [comment]
Yeah, I was also assuming that a port of nREPL must be done.
Thanks for looking into this.

I'm wondering if a language server for clojerl (like this: https://github.com/snoe/clojure-lsp)
plus clojure-mode and eglot or lsp-mode on Emacs side would also do.
It's not as convenient as a full fletched IDE like CIDER but works fairly well.
I do that with ElixirLS and Eglot.

**Comment by jfacorro** [comment]
A language server would definitely go a long way to improving the experience. 

The implementation could include some custom commands to start and interact with a running REPL. As a first stab at this the server could use the out of the box REPL over TCP server that comes with Clojure and is included in Clojerl [here](https://github.com/clojerl/clojerl/blob/master/src/clj/clojure/core/server.clje), to avoid having to implement an nREPL server (although that could be fun 😄).

**Comment by mdbergmann** [comment]
> A language server would definitely go a long way to improving the experience.
definitely. If possible it should be based on CIDER.

**Comment by jfacorro** [comment]
> If possible it should be based on CIDER.

Do you mean taking CIDER's features as a reference?

**Comment by mdbergmann** [comment]
I'm not sure.

Generally I'd say that CIDER's features are super.
And if somewhere possible it would be good if those could be used.
However, as you said yourself, there are quite some unknowns as to what is additionally needed to make it work with Clojerl.

The nREPL port could be the most simple thing, if there are no dependencies.

I'd say the course should be something that is doable to something that works (even though imperfect), within a reasonable time.
What would you suggest?

**Comment by jfacorro** [comment]
I think creating an nREPL would be the first step. Even if we can't use it with CIDER, it would be possible to use it with other nREPL clients (e.g. https://github.com/sanel/monroe), so it wouldn't be wasted work and it does sound like a nice project in itself. If you want to work on this I can create a `nrepl` repository under the clojerl github organization for you.

The next step would be either spending a little bit of time checking how hard it would be to hook `rebar3+rebar3_clojerl` projects into CIDER. If that proves too complicated or not worth the effort, we could then decide to go for the LSP server, which also sounds like an interesting project. There are some existing implementations that don't rely on a running REPL (e.g. the one you linked https://github.com/snoe/clojure-lsp).

**Comment by mdbergmann** [comment]
OK, that sounds like a plan.
If you could create a nrepl repo that would be great.

I'd be interested to look into it, even though my spare time is tight.

**Comment by jfacorro** [comment]
Repository created https://github.com/clojerl/nrepl 🎉  and you are added as a collaborator.

Let me know if you need any assistance, either setting up the project or anything else.

**Comment by jfacorro** [comment]
I will close this issue and we can track the progress.

**Comment by mdbergmann** [comment]
Yep, that's fine.

**Comment by darth10** [comment]
Is [clojerl/nrepl](https://github.com/clojerl/nrepl) in a fairly usable state now?
The repo's README doesn't have a lot of information so I thought I'd ask here.

**Comment by jfacorro** [comment]
@darth10 I'm not sure, @mdbergmann has been mainly dedicating time to this effort. I will check with him and maybe we can get something working.

**Comment by mdbergmann** [comment]
Hi.
Unfortunately I have not had much time to work on it. It's still a long way from something that works.
